/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edu.sise.capas.gui;

import com.edu.sise.capas.entity.Usuario;
import com.edu.sise.capas.logic.UsuarioLogic;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author meryj
 */
public class iFrmUsuarios extends javax.swing.JInternalFrame {
    UsuarioLogic logic = null;

    /**
     * Creates new form iFrmUsuarios
     */
    public iFrmUsuarios() {
        initComponents();
        logic = new UsuarioLogic();
        logic.imprimirTB(tbListaUsuarios, logic.obtenerTodos());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnObtener = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtClave = new javax.swing.JTextField();
        btnListar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbListaUsuarios = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtBuscarxNombre = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setTitle("Mantenedor Usuarios");

        jLabel1.setText("ID");

        btnObtener.setText("Obtener");
        btnObtener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObtenerActionPerformed(evt);
            }
        });

        jLabel2.setText("NOMBRE");

        jLabel3.setText("CLAVE");

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        tbListaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbListaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbListaUsuarios);

        jLabel4.setText("BUSCAR");

        txtBuscarxNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarxNombreKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarxNombreKeyReleased(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscarxNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(btnModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEliminar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtClave)
                                            .addComponent(txtNombre))
                                        .addGap(23, 23, 23)
                                        .addComponent(btnObtener)))))
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListar))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnObtener))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar)
                    .addComponent(btnAgregar)
                    .addComponent(btnEliminar))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtBuscarxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnObtenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObtenerActionPerformed
        // TODO add your handling code here:
        logic = new UsuarioLogic();
        
        int  id = Integer.parseInt(txtId.getText());
        Usuario objUsuario = logic.obtenerUsuarioxID(id);
        if(objUsuario!=null){
            JOptionPane.showMessageDialog(null, "Bienvenido " +  objUsuario.getNombre());
        }else{
            JOptionPane.showMessageDialog(null, "No se pudo obtener el usuario");
        }
        
    }//GEN-LAST:event_btnObtenerActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int id;
        boolean rptaEliminado;        
        int fila;
        fila = tbListaUsuarios.getSelectedRow();
        if(fila>=0){
            id = Integer.parseInt(tbListaUsuarios.getValueAt(fila, 0) + ""); 
            
            int valor = JOptionPane.showConfirmDialog(null, "¿Desea realmente eliminar el registro?","Sistema",JOptionPane.YES_NO_OPTION);
            if (valor ==JOptionPane.YES_OPTION){
                logic = new UsuarioLogic();
                rptaEliminado = logic.eliminarUsuario(id);
                if(rptaEliminado){
                    JOptionPane.showMessageDialog(null, "Se elimino correctamente!!!");
                }else{
                    JOptionPane.showMessageDialog(null, "No se pudo eliminar :(");
                }
                logic.imprimirTB(tbListaUsuarios, logic.obtenerTodos());
                
            }
            
        }
        
//        boolean rptaEliminado;
//        rpta = JOptionPane.showInputDialog(null, "Ingrese el ID del Usuario a eliminar: ");
//        
//        if(rpta!=null){
//            id = Integer.parseInt(rpta);
//            logic = new UsuarioLogic();
//            rptaEliminado = logic.eliminarUsuario(id);
//            
//            if(rptaEliminado){
//                JOptionPane.showMessageDialog(null, "Se elimino correctamente!!!");
//            }else{
//                JOptionPane.showMessageDialog(null, "No se pudo eliminar :(");
//            }
//            logic.imprimirTB(tbListaUsuarios, logic.obtenerTodos());
//        }
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // TODO add your handling code here:
        logic = new UsuarioLogic();
        logic.imprimirTB(tbListaUsuarios, logic.obtenerTodos());
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        //codigo para agregar un registro
//        Usuario objUsuario = new Usuario();
//        int id;
//        String nombre, clave;
//        id = Integer.parseInt(txtId.getText());
//        nombre = txtNombre.getText();
//        clave = txtClave.getText();
//        objUsuario.setId_usuario(id);
//        objUsuario.setNombre(nombre);
//        objUsuario.setClave(clave);
        logic = new UsuarioLogic();
        boolean rpta;
        rpta = logic.agregarUsuario(getUsuario());
        
        if (rpta){
            JOptionPane.showMessageDialog(null, "Se registro correctamente!!!");
        }else{
            JOptionPane.showMessageDialog(null, "No se pudo registrar :( "); 
        }
         logic.imprimirTB(tbListaUsuarios, logic.obtenerTodos());
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void tbListaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListaUsuariosMouseClicked
        // TODO add your handling code here:
        int fila;
        fila = tbListaUsuarios.getSelectedRow();
        System.out.println("Fila: " + fila);
        
        int id;
        String nombre, clave;
        
        if (fila>=0){
            //columnas: ID - NOMBRE - CLAVE
            //POSICIONES: 0 - 1 - 2
            id = Integer.parseInt(tbListaUsuarios.getValueAt(fila, 0) + "");
            nombre = tbListaUsuarios.getValueAt(fila, 1) + "";
            clave = tbListaUsuarios.getValueAt(fila, 2) + "";
            txtId.setText(id + "");
            txtNombre.setText(nombre);
            txtClave.setText(clave);
            
        }
    }//GEN-LAST:event_tbListaUsuariosMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
//        Usuario objUsuario = new Usuario();
//        objUsuario.setId_usuario(Integer.parseInt(txtId.getText()));
//        objUsuario.setNombre(txtNombre.getText());
//        objUsuario.setClave(txtClave.getText());
        
        logic = new UsuarioLogic();
        boolean rpta = logic.modificarUsuario(getUsuario());
        
        if(rpta){
            JOptionPane.showMessageDialog(null, "Se modifico correctamente!!!");
        }else{
            JOptionPane.showMessageDialog(null, "No se pudo modificar :(");
        }
        logic.imprimirTB(tbListaUsuarios, logic.obtenerTodos());
                
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String nombreBuscar = txtBuscarxNombre.getText();
        logic = new UsuarioLogic();
        logic.imprimirTB(tbListaUsuarios, logic.buscarxNombre(nombreBuscar));
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtBuscarxNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarxNombreKeyPressed
        // TODO add your handling code here:
        String nombreBuscar = txtBuscarxNombre.getText();
        logic = new UsuarioLogic();
        logic.imprimirTB(tbListaUsuarios, logic.buscarxNombre(nombreBuscar));
    }//GEN-LAST:event_txtBuscarxNombreKeyPressed

    private void txtBuscarxNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarxNombreKeyReleased
        // TODO add your handling code here:
        String nombreBuscar = txtBuscarxNombre.getText();
        logic = new UsuarioLogic();
        logic.imprimirTB(tbListaUsuarios, logic.buscarxNombre(nombreBuscar));
    }//GEN-LAST:event_txtBuscarxNombreKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnObtener;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tbListaUsuarios;
    private javax.swing.JTextField txtBuscarxNombre;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    Usuario getUsuario(){
        Usuario objUsuario = new Usuario(
                Integer.parseInt(txtId.getText()),
                txtNombre.getText(), 
                txtClave.getText());
        return objUsuario;
    }

}



